### ISSUE TITLE
Code coverage using unit tests

### ISSUE THREAD

**Issue by devkhan** [SBRG/EscherConverter#1]
I noticed this repo does not have any unit tests. Has it always been like this or have they been removed or somewhere else. Should I start adding some? I'll open a WIP PR so you can review and for discussion before merging into master.

/cc @draeger @zakandrewking

**Comment by zakandrewking** [comment]
What do you think Andreas? Does it make more sense to focus on a new codebase instead?

On the other hand, writing unit tests is a fantastic way to understand how the code works.

**Comment by draeger** [comment]
EscherConverter used to be part of a different software project and has now become its own repository. I totally agree, adding unit tests is clearly a great way to get started. Please let me know if anything is unclear or doesn't work in this new configuration.

**Comment by devkhan** [comment]
@zakandrewking @draeger Thanks. I'll get started and try to add some unit tests to this.

**Comment by devkhan** [comment]
As we talked, we need to refactor first. So, should I first refactor or get started with writing tests right away, as they may break later. Also, we need to strip off some more code first, so I think first priority should be refactoring and getting it to run and properly convert a file first.
