### ISSUE TITLE
Version not showing up

### ISSUE THREAD

**Issue by devkhan** [SBRG/EscherConverter#17]
Trying to export SBML:

```xml
<!-- Created by EscherConverter version @app.version@ on 2016-17-22 at 15:17:22 IST with JSBML version 1.1. -->
```

Have to figure out why version property is not written. Will do it later.

**Comment by draeger** [comment]
This is solved now. The current version number is always taken from the launcher class (see method `public String getVersionNumber()`). The String `@app.version@` was there for historic reasons: before switching to Maven, an Ant build script was used to replace this value upon building a new release. Now, Maven does essentially the same. The version number is taken from the POM file upon building and will replace a placeholder `String` in the file `edu.ucsd.sbrg.escher.Messages`. Binaries now always know this version number and write it correctly into the SBML.
