### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by devkhan** [SBRG/EscherConverter#2]
So, I was trying to build this project using IntelliJ IDEA with Maven build system. At first, it didn't auto-detect any libs, so I manually added the jars in the `libs` directory. But now it throwing the following error:

![image](https://cloud.githubusercontent.com/assets/8049092/14424132/1dbbd896-fffd-11e5-81ff-23f494418669.png)

Also, when I looked into the jar, there wasn't any package named `actioncommand`, what could be the problem?

/cc @draeger @zakandrewking

**Comment by draeger** [comment]
This should be fixed now; all dependencies that are not in a central Maven repository yet are now defined in a local repository. Please let me know if it works now.

**Comment by devkhan** [comment]
Yes, I am to build now and the command line jar is running fine.

Thanks.
