### ISSUE TITLE
Error in test SBGN file validation

### ISSUE THREAD

**Issue by devkhan** [SBRG/EscherConverter#5]
The jar is runnable now, and it also shows the options properly. But the following error still shows up before starting. I've placed a `test.sbgn` file at the appropriate place.

```
java.lang.NullPointerException
	at org.sbgn.schematron.SchematronValidator.doValidation(SchematronValidator.java:72)
	at org.sbgn.schematron.SchematronValidator.validate(SchematronValidator.java:46)
	at edu.ucsd.sbrg.escher.EscherConverter.main(EscherConverter.java:163)
objc[8317]: Class SheetSupport is implemented in both <br />
<PROJECT_DIR>/EscherConverter/libquaqua64.jnilib and <PROJECT_DIR>/EscherConverter/libquaqua64.dylib. One of the two will be used. Which one is undefined.
```

**Comment by draeger** [comment]
Yes, SBGN validation is troublesome. We should put this on our agenda for the Friday meeting.

**Comment by devkhan** [comment]
Found the cause: The method `SchematronValidator.doValidation(File)` throws `NullPointerException` at L72 if no language attribute is specified on the map element. We can add a check to ensure a language attribute is present.

**Comment by devkhan** [comment]
Removed the test file validation in 7a6207834a20610a1111b0cf00ed1373fd01fc2a. Will add later for converted files.
